name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      -completed

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Pull Docker Image
      run: sudo docker pull  viveksantoki008/books-project-app:latest
    - name: Delete old Docker Container
      run: sudo docker rm -f books-project-app-container || true
    - name: Run Docker Container with Latest Image
      run: sudo docker run -d -p 8000:8000 --name books-project-app-container viveksantoki008/books-project-app
